<?php

/**
 * This is the model base class for the table "banner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Banner".
 *
 * Columns in table "banner" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idbanner
 * @property string $habilitar
 * @property string $nova_aba
 * @property string $data
 * @property string $titulo
 * @property string $local
 * @property string $data_entrada
 * @property string $data_saida
 * @property string $link
 * @property string $imagem
 * @property integer $posicao
 *
 */
abstract class BaseBanner extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banner';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Banner|Banners', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('habilitar, nova_aba', 'required'),
			array('posicao', 'numerical', 'integerOnly'=>true),
			array('habilitar, nova_aba', 'length', 'max'=>1),
			array('titulo', 'length', 'max'=>100),
			array('local', 'length', 'max'=>150),
			array('link', 'length', 'max'=>200),
			array('imagem', 'length', 'max'=>160),
			array('data, data_entrada, data_saida', 'safe'),
			array('data, titulo, local, data_entrada, data_saida, link, imagem, posicao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idbanner, habilitar, nova_aba, data, titulo, local, data_entrada, data_saida, link, imagem, posicao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idbanner' => Yii::t('app', 'Idbanner'),
			'habilitar' => Yii::t('app', 'Habilitar'),
			'nova_aba' => Yii::t('app', 'Nova Aba'),
			'data' => Yii::t('app', 'Data'),
			'titulo' => Yii::t('app', 'Titulo'),
			'local' => Yii::t('app', 'Local'),
			'data_entrada' => Yii::t('app', 'Data Entrada'),
			'data_saida' => Yii::t('app', 'Data Saida'),
			'link' => Yii::t('app', 'Link'),
			'imagem' => Yii::t('app', 'Imagem'),
			'posicao' => Yii::t('app', 'Posicao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idbanner', $this->idbanner);
		$criteria->compare('habilitar', $this->habilitar, true);
		$criteria->compare('nova_aba', $this->nova_aba, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('local', $this->local, true);
		$criteria->compare('data_entrada', $this->data_entrada, true);
		$criteria->compare('data_saida', $this->data_saida, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('posicao', $this->posicao);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}