<?php

/**
 * This is the model base class for the table "perfil".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Perfil".
 *
 * Columns in table "perfil" available as properties of the model,
 * followed by relations of table "perfil" available as properties of the model.
 *
 * @property integer $idperfil
 * @property string $habilitar
 * @property string $excluido
 * @property string $nome
 * @property string $permissao
 *
 * @property Usuario[] $usuarios
 */
abstract class BasePerfil extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'perfil';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Perfil|Perfis', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('habilitar, excluido', 'length', 'max'=>1),
			array('nome', 'length', 'max'=>100),
			array('permissao', 'safe'),
			array('habilitar, excluido, nome, permissao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idperfil, habilitar, excluido, nome, permissao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarios' => array(self::HAS_MANY, 'Usuario', 'idperfil'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idperfil' => Yii::t('app', 'Idperfil'),
			'habilitar' => Yii::t('app', 'Habilitar'),
			'excluido' => Yii::t('app', 'Excluido'),
			'nome' => Yii::t('app', 'Nome'),
			'permissao' => Yii::t('app', 'Permissões'),
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idperfil', $this->idperfil);
		$criteria->compare('habilitar', $this->habilitar, true);
		$criteria->compare('excluido', $this->excluido, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('permissao', $this->permissao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}