<?php

/**
 * This is the model base class for the table "representante".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Representante".
 *
 * Columns in table "representante" available as properties of the model,
 * followed by relations of table "representante" available as properties of the model.
 *
 * @property integer $idrepresentante
 * @property string $habilitar
 * @property string $nome
 * @property string $foto
 * @property string $telefone
 * @property string $email
 * @property string $regiao_atuacao
 *
 * @property Cliente[] $clientes
 * @property HistoricoVendas[] $historicoVendases
 */
abstract class BaseRepresentante extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'representante';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Representante|Representantes', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('habilitar', 'required'),
			array('habilitar', 'length', 'max'=>1),
			array('nome', 'length', 'max'=>100),
			array('foto', 'length', 'max'=>160),
			array('regiao_atuacao', 'length', 'max'=>150),
			array('telefone, email', 'safe'),
			array('nome, foto, telefone, email, regiao_atuacao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idrepresentante, habilitar, nome, foto, telefone, email, regiao_atuacao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientes' => array(self::HAS_MANY, 'Cliente', 'idrepresentante'),
			'historicoVendases' => array(self::HAS_MANY, 'HistoricoVendas', 'idrepresentante'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idrepresentante' => Yii::t('app', 'Idrepresentante'),
			'habilitar' => Yii::t('app', 'Habilitar'),
			'nome' => Yii::t('app', 'Nome'),
			'foto' => Yii::t('app', 'Foto'),
			'telefone' => Yii::t('app', 'Telefone'),
			'email' => Yii::t('app', 'Email'),
			'regiao_atuacao' => Yii::t('app', 'Região de Atuação'),
			'clientes' => null,
			'historicoVendases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idrepresentante', $this->idrepresentante);
		$criteria->compare('habilitar', $this->habilitar, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('foto', $this->foto, true);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('regiao_atuacao', $this->regiao_atuacao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}