<?php

/**
 * This is the model base class for the table "historico_vendas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HistoricoVendas".
 *
 * Columns in table "historico_vendas" available as properties of the model,
 * followed by relations of table "historico_vendas" available as properties of the model.
 *
 * @property integer $idvenda
 * @property string $data_venda
 * @property integer $idcliente
 * @property integer $idproduto
 * @property integer $quantidade
 * @property double $valor_unitario
 * @property double $valor_total
 * @property integer $idrepresentante
 *
 * @property Cliente $cliente
 * @property Produto $produto
 * @property Representante $representante
 */
abstract class BaseHistoricoVendas extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'historico_vendas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Historico de Venda|Historico de Vendas', $n);
	}

	public static function representingColumn() {
		return array('data_venda');
	}

	

	public function rules() {
		return array(
			array('data_venda, idcliente, idproduto, quantidade, valor_unitario, valor_total, idrepresentante', 'required'),
	
			array('idcliente, idproduto, quantidade, idrepresentante', 'numerical', 'integerOnly'=>true),
			array('valor_unitario, valor_total', 'numerical'),
			array('idvenda, data_venda, idcliente, idproduto, quantidade, valor_unitario, valor_total, idrepresentante', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cliente' => array(self::BELONGS_TO, 'Cliente', 'idcliente'),
			'produto' => array(self::BELONGS_TO, 'Produto', 'idproduto'),
			'representante' => array(self::BELONGS_TO, 'Representante', 'idrepresentante'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idvenda' => Yii::t('app', 'Idvenda'),
			'habilitar' => Yii::t('app', 'Habilitar'),
			'data_venda' => Yii::t('app', 'Data da Venda'),
			'idcliente' => null,
			'idproduto' => null,
			'quantidade' => Yii::t('app', 'Quantidade'),
			'valor_unitario' => Yii::t('app', 'Valor Unitario do produto'),
			'valor_total' => Yii::t('app', 'Valor Total'),
			'idrepresentante' => null,
			'cliente' => null,
			'produto' => null,
			'representante' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idvenda', $this->idvenda);
		$criteria->compare('habilitar', $this->habilitar, true);
		$criteria->compare('data_venda', $this->data_venda, true);
		$criteria->compare('idcliente', $this->idcliente);
		$criteria->compare('idproduto', $this->idproduto);
		$criteria->compare('quantidade', $this->quantidade);
		$criteria->compare('valor_unitario', $this->valor_unitario);
		$criteria->compare('valor_total', $this->valor_total);
		$criteria->compare('idrepresentante', $this->idrepresentante);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}