<?php

/**
 * This is the model base class for the table "cidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cidade".
 *
 * Columns in table "cidade" available as properties of the model,
 * followed by relations of table "cidade" available as properties of the model.
 *
 * @property integer $idcidade
 * @property string $nome
 * @property string $uf
 * @property string $habilitar
 *
 * @property Cliente[] $clientes
 */
abstract class BaseCidade extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cidade';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cidade|Cidades', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('idcidade', 'required'),
			array('idcidade', 'numerical', 'integerOnly'=>true),
			array('nome', 'length', 'max'=>100),
			array('uf', 'length', 'max'=>2),
			array('habilitar', 'length', 'max'=>1),
			array('nome, uf, habilitar', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcidade, nome, uf, habilitar', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientes' => array(self::HAS_MANY, 'Cliente', 'idcidade'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcidade' => Yii::t('app', 'Idcidade'),
			'nome' => Yii::t('app', 'Nome'),
			'uf' => Yii::t('app', 'Uf'),
			'habilitar' => Yii::t('app', 'Habilitar'),
			'clientes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcidade', $this->idcidade);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('uf', $this->uf, true);
		$criteria->compare('habilitar', $this->habilitar, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}