<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * followed by relations of table "usuario" available as properties of the model.
 *
 * @property integer $idusuario
 * @property string $habilitar
 * @property string $excluido
 * @property string $nome
 * @property integer $idperfil
 * @property string $email
 * @property string $senha
 *
 * @property Perfil $perfil
 */
abstract class BaseUsuario extends GxActiveRecord {

	public $senha_confirma;
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuário|Usuários', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('idperfil', 'required'),
			array('idperfil', 'numerical', 'integerOnly'=>true),
			array('habilitar, excluido', 'length', 'max'=>1),
			array('nome, email, senha, senha_confirma', 'length', 'max'=>100),
			array('habilitar, excluido, nome, email, senha', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idusuario, habilitar, excluido, nome, idperfil, email, senha,senha_confirma', 'safe', 'on'=>'search'),
			//Campos obrigatórios
			array('senha,senha_confirma', 'required', 'on'=>'insert'),
			
			array('email', 'unique',  'criteria' => array(
				'condition' => "idusuario != '".$this->idusuario."'",
			)),
			
			//Campos que devem ser iguais
			array('senha','compare', 'compareAttribute'=>'senha_confirma', 'message'=>"As senhas informadas são diferentes"),
			
			
		);
	}

	public function relations() {
		return array(
			'perfil' => array(self::BELONGS_TO, 'Perfil', 'idperfil'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idusuario' => Yii::t('app', 'Idusuario'),
			'habilitar' => Yii::t('app', 'Habilitar'),
			'excluido' => Yii::t('app', 'Excluido'),
			'nome' => Yii::t('app', 'Nome'),
			'idperfil' =>Yii::t('app', 'Perfil'),
			'email' => Yii::t('app', 'Email'),
			'senha' => Yii::t('app', 'Senha'),
			'perfil' => null,
			'senha_confirma' => "Confirme a senha",
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idusuario', $this->idusuario);
		$criteria->compare('habilitar', $this->habilitar, true);
		$criteria->compare('excluido', $this->excluido, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('idperfil', $this->idperfil);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('senha', $this->senha, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}