<?php

/**
 * This is the model base class for the table "categoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Categoria".
 *
 * Columns in table "categoria" available as properties of the model,
 * followed by relations of table "categoria" available as properties of the model.
 *
 * @property integer $idcategoria
 * @property string $habilitar
 * @property string $nome
 * @property string $descricao
 * @property integer $posicao
 *
 * @property Produto[] $produtos
 */
abstract class BaseCategoria extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'categoria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Categoria|Categorias', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('habilitar', 'required'),
			array('posicao', 'numerical', 'integerOnly'=>true),
			array('habilitar', 'length', 'max'=>1),
			array('nome', 'length', 'max'=>100),
			array('descricao', 'safe'),
			array('nome, descricao, posicao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcategoria, habilitar, nome, descricao, posicao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'produtos' => array(self::HAS_MANY, 'Produto', 'idcategoria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcategoria' => Yii::t('app', 'Idcategoria'),
			'habilitar' => Yii::t('app', 'Habilitar'),
			'nome' => Yii::t('app', 'Nome'),
			'descricao' => Yii::t('app', 'Descrição'),
			'posicao' => Yii::t('app', 'Posição'),
			'produtos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcategoria', $this->idcategoria);
		$criteria->compare('habilitar', $this->habilitar, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('posicao', $this->posicao);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}